preview_entity_cache:
  enabled: true
  subgraph:
    all:
      enabled: true
      redis:
        urls: ['redis://localhost:6379']
        ttl: 20s
headers:
  all:
    request:
      - propagate:
          named: 'authorization'
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs
